name: Winston Bot Develop
# trigger on
on:
  # trigger workflow when push is received on develop branch
  # trigger workflow when merge request is received on develop branch
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  winston_develop:
    name: Winston Bot Development
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run test
    - run: npm run build --if-present
    - run: pm2 restart "Winston Bot"
      env:
        CI: true
